# Generated by Django 3.1 on 2020-08-06 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appInfo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='version',
            field=models.FloatField(),
        ),
    ]
